-- STORED PROCEDURES
CREATE DEFINER=`root`@`localhost` PROCEDURE `getGamesForSummoner`(IN sum_id BIGINT(20))
BEGIN
	SELECT * FROM game
	LEFT JOIN player ON game.id = player.match_id
	WHERE player.summoner_id = sum_id
	LIMIT 100;
END;

--  DATA

INSERT INTO `role` (`id`, `type`) VALUES ('1', 'ADMIN');
INSERT INTO `role` (`id`, `type`) VALUES ('2', 'USER');
INSERT INTO `user` (`id`, `active`, `created_at`, `email`, `password`, `removed`, `username`) VALUES ('24670397', '1', '2016-12-15 12:22:05', 'ff@20.gg', '$2a$10$GOqit2ZkhaV/NW.8KpK7xOBwapeHK1YkIqUpzG4YJiisVdxfo69G6', '0', 'oliwer94');
INSERT INTO `user_role` (`user_id`, `role_id`) VALUES ('24670397', '2');
INSERT INTO `user` (`id`, `active`, `created_at`, `email`, `password`, `removed`, `username`) VALUES ('19652129', '1', '2016-12-15 12:22:05', 'ff@20.gg', '$2a$10$GOqit2ZkhaV/NW.8KpK7xOBwapeHK1YkIqUpzG4YJiisVdxfo69G6', '0', 'FigaPl');
INSERT INTO `user_role` (`user_id`, `role_id`) VALUES ('19652129', '1');

INSERT INTO `champion` (`id`, `name`) VALUES ('266', 'Aatrox');
INSERT INTO `champion` (`id`, `name`) VALUES ('103', 'Ahri');
INSERT INTO `champion` (`id`, `name`) VALUES ('84', 'Akali');
INSERT INTO `champion` (`id`, `name`) VALUES ('12', 'Alistar');
INSERT INTO `champion` (`id`, `name`) VALUES ('32', 'Amumu');
INSERT INTO `champion` (`id`, `name`) VALUES ('34', 'Anivia');
INSERT INTO `champion` (`id`, `name`) VALUES ('1', 'Annie');
INSERT INTO `champion` (`id`, `name`) VALUES ('22', 'Ashe');
INSERT INTO `champion` (`id`, `name`) VALUES ('136', 'Aurelion Sol');
INSERT INTO `champion` (`id`, `name`) VALUES ('268', 'Azir');
INSERT INTO `champion` (`id`, `name`) VALUES ('432', 'Bard');
INSERT INTO `champion` (`id`, `name`) VALUES ('53', 'Blitzcrank');
INSERT INTO `champion` (`id`, `name`) VALUES ('63', 'Brand');
INSERT INTO `champion` (`id`, `name`) VALUES ('201', 'Braum');
INSERT INTO `champion` (`id`, `name`) VALUES ('51', 'Caitlyn');
INSERT INTO `champion` (`id`, `name`) VALUES ('164', 'Camille');
INSERT INTO `champion` (`id`, `name`) VALUES ('69', 'Cassiopeia');
INSERT INTO `champion` (`id`, `name`) VALUES ('31', 'Cho\'Gath');
INSERT INTO `champion` (`id`, `name`) VALUES ('42', 'Corki');
INSERT INTO `champion` (`id`, `name`) VALUES ('122', 'Darius');
INSERT INTO `champion` (`id`, `name`) VALUES ('131', 'Diana');
INSERT INTO `champion` (`id`, `name`) VALUES ('36', 'Dr. Mundo');
INSERT INTO `champion` (`id`, `name`) VALUES ('119', 'Draven');
INSERT INTO `champion` (`id`, `name`) VALUES ('245', 'Ekko');
INSERT INTO `champion` (`id`, `name`) VALUES ('60', 'Elise');
INSERT INTO `champion` (`id`, `name`) VALUES ('28', 'Evelynn');
INSERT INTO `champion` (`id`, `name`) VALUES ('81', 'Ezreal');
INSERT INTO `champion` (`id`, `name`) VALUES ('9', 'Fiddlesticks');
INSERT INTO `champion` (`id`, `name`) VALUES ('114', 'Fiora');
INSERT INTO `champion` (`id`, `name`) VALUES ('105', 'Fizz');
INSERT INTO `champion` (`id`, `name`) VALUES ('3', 'Galio');
INSERT INTO `champion` (`id`, `name`) VALUES ('41', 'Gangplank');
INSERT INTO `champion` (`id`, `name`) VALUES ('86', 'Garen');
INSERT INTO `champion` (`id`, `name`) VALUES ('150', 'Gnar');
INSERT INTO `champion` (`id`, `name`) VALUES ('79', 'Gragas');
INSERT INTO `champion` (`id`, `name`) VALUES ('104', 'Graves');
INSERT INTO `champion` (`id`, `name`) VALUES ('120', 'Hecarim');
INSERT INTO `champion` (`id`, `name`) VALUES ('74', 'Heimerdinger');
INSERT INTO `champion` (`id`, `name`) VALUES ('420', 'Illaoi');
INSERT INTO `champion` (`id`, `name`) VALUES ('39', 'Irelia');
INSERT INTO `champion` (`id`, `name`) VALUES ('427', 'Ivern');
INSERT INTO `champion` (`id`, `name`) VALUES ('40', 'Janna');
INSERT INTO `champion` (`id`, `name`) VALUES ('59', 'Jarvan IV');
INSERT INTO `champion` (`id`, `name`) VALUES ('24', 'Jax');
INSERT INTO `champion` (`id`, `name`) VALUES ('126', 'Jayce');
INSERT INTO `champion` (`id`, `name`) VALUES ('202', 'Jhin');
INSERT INTO `champion` (`id`, `name`) VALUES ('222', 'Jinx');
INSERT INTO `champion` (`id`, `name`) VALUES ('429', 'Kalista');
INSERT INTO `champion` (`id`, `name`) VALUES ('43', 'Karma');
INSERT INTO `champion` (`id`, `name`) VALUES ('30', 'Karthus');
INSERT INTO `champion` (`id`, `name`) VALUES ('38', 'Kassadin');
INSERT INTO `champion` (`id`, `name`) VALUES ('55', 'Katarina');
INSERT INTO `champion` (`id`, `name`) VALUES ('10', 'Kayle');
INSERT INTO `champion` (`id`, `name`) VALUES ('85', 'Kennen');
INSERT INTO `champion` (`id`, `name`) VALUES ('121', 'Kha\'Zix');
INSERT INTO `champion` (`id`, `name`) VALUES ('203', 'Kindred');
INSERT INTO `champion` (`id`, `name`) VALUES ('240', 'Kled');
INSERT INTO `champion` (`id`, `name`) VALUES ('96', 'Kog\'Maw');
INSERT INTO `champion` (`id`, `name`) VALUES ('7', 'LeBlanc');
INSERT INTO `champion` (`id`, `name`) VALUES ('64', 'Lee Sin');
INSERT INTO `champion` (`id`, `name`) VALUES ('89', 'Leona');
INSERT INTO `champion` (`id`, `name`) VALUES ('127', 'Lissandra');
INSERT INTO `champion` (`id`, `name`) VALUES ('236', 'Lucian');
INSERT INTO `champion` (`id`, `name`) VALUES ('117', 'Lulu');
INSERT INTO `champion` (`id`, `name`) VALUES ('99', 'Lux');
INSERT INTO `champion` (`id`, `name`) VALUES ('54', 'Malphite');
INSERT INTO `champion` (`id`, `name`) VALUES ('90', 'Malzahar');
INSERT INTO `champion` (`id`, `name`) VALUES ('57', 'Maokai');
INSERT INTO `champion` (`id`, `name`) VALUES ('11', 'Master Yi');
INSERT INTO `champion` (`id`, `name`) VALUES ('21', 'Miss Fortune');
INSERT INTO `champion` (`id`, `name`) VALUES ('82', 'Mordekaiser');
INSERT INTO `champion` (`id`, `name`) VALUES ('25', 'Morgana');
INSERT INTO `champion` (`id`, `name`) VALUES ('267', 'Nami');
INSERT INTO `champion` (`id`, `name`) VALUES ('75', 'Nasus');
INSERT INTO `champion` (`id`, `name`) VALUES ('111', 'Nautilus');
INSERT INTO `champion` (`id`, `name`) VALUES ('76', 'Nidalee');
INSERT INTO `champion` (`id`, `name`) VALUES ('56', 'Nocturne');
INSERT INTO `champion` (`id`, `name`) VALUES ('20', 'Nunu');
INSERT INTO `champion` (`id`, `name`) VALUES ('2', 'Olaf');
INSERT INTO `champion` (`id`, `name`) VALUES ('61', 'Orianna');
INSERT INTO `champion` (`id`, `name`) VALUES ('80', 'Pantheon');
INSERT INTO `champion` (`id`, `name`) VALUES ('78', 'Poppy');
INSERT INTO `champion` (`id`, `name`) VALUES ('133', 'Quinn');
INSERT INTO `champion` (`id`, `name`) VALUES ('33', 'Rammus');
INSERT INTO `champion` (`id`, `name`) VALUES ('421', 'Rek\'Sai');
INSERT INTO `champion` (`id`, `name`) VALUES ('58', 'Renekton');
INSERT INTO `champion` (`id`, `name`) VALUES ('107', 'Rengar');
INSERT INTO `champion` (`id`, `name`) VALUES ('92', 'Riven');
INSERT INTO `champion` (`id`, `name`) VALUES ('68', 'Rumble');
INSERT INTO `champion` (`id`, `name`) VALUES ('13', 'Ryze');
INSERT INTO `champion` (`id`, `name`) VALUES ('113', 'Sejuani');
INSERT INTO `champion` (`id`, `name`) VALUES ('35', 'Shaco');
INSERT INTO `champion` (`id`, `name`) VALUES ('98', 'Shen');
INSERT INTO `champion` (`id`, `name`) VALUES ('102', 'Shyvana');
INSERT INTO `champion` (`id`, `name`) VALUES ('27', 'Singed');
INSERT INTO `champion` (`id`, `name`) VALUES ('14', 'Sion');
INSERT INTO `champion` (`id`, `name`) VALUES ('15', 'Sivir');
INSERT INTO `champion` (`id`, `name`) VALUES ('72', 'Skarner');
INSERT INTO `champion` (`id`, `name`) VALUES ('37', 'Sona');
INSERT INTO `champion` (`id`, `name`) VALUES ('16', 'Soraka');
INSERT INTO `champion` (`id`, `name`) VALUES ('50', 'Swain');
INSERT INTO `champion` (`id`, `name`) VALUES ('134', 'Syndra');
INSERT INTO `champion` (`id`, `name`) VALUES ('223', 'Tahm Kench');
INSERT INTO `champion` (`id`, `name`) VALUES ('163', 'Taliyah');
INSERT INTO `champion` (`id`, `name`) VALUES ('91', 'Talon');
INSERT INTO `champion` (`id`, `name`) VALUES ('44', 'Taric');
INSERT INTO `champion` (`id`, `name`) VALUES ('17', 'Teemo');
INSERT INTO `champion` (`id`, `name`) VALUES ('412', 'Thresh');
INSERT INTO `champion` (`id`, `name`) VALUES ('18', 'Tristana');
INSERT INTO `champion` (`id`, `name`) VALUES ('48', 'Trundle');
INSERT INTO `champion` (`id`, `name`) VALUES ('23', 'Tryndamere');
INSERT INTO `champion` (`id`, `name`) VALUES ('4', 'Twisted Fate');
INSERT INTO `champion` (`id`, `name`) VALUES ('29', 'Twitch');
INSERT INTO `champion` (`id`, `name`) VALUES ('77', 'Udyr');
INSERT INTO `champion` (`id`, `name`) VALUES ('6', 'Urgot');
INSERT INTO `champion` (`id`, `name`) VALUES ('110', 'Varus');
INSERT INTO `champion` (`id`, `name`) VALUES ('67', 'Vayne');
INSERT INTO `champion` (`id`, `name`) VALUES ('45', 'Veigar');
INSERT INTO `champion` (`id`, `name`) VALUES ('161', 'Vel\'Koz');
INSERT INTO `champion` (`id`, `name`) VALUES ('254', 'Vi');
INSERT INTO `champion` (`id`, `name`) VALUES ('112', 'Viktor');
INSERT INTO `champion` (`id`, `name`) VALUES ('8', 'Vladimir');
INSERT INTO `champion` (`id`, `name`) VALUES ('106', 'Volibear');
INSERT INTO `champion` (`id`, `name`) VALUES ('19', 'Warwick');
INSERT INTO `champion` (`id`, `name`) VALUES ('62', 'Wukong');
INSERT INTO `champion` (`id`, `name`) VALUES ('101', 'Xerath');
INSERT INTO `champion` (`id`, `name`) VALUES ('5', 'Xin Zhao');
INSERT INTO `champion` (`id`, `name`) VALUES ('157', 'Yasuo');
INSERT INTO `champion` (`id`, `name`) VALUES ('83', 'Yorick');
INSERT INTO `champion` (`id`, `name`) VALUES ('154', 'Zac');
INSERT INTO `champion` (`id`, `name`) VALUES ('238', 'Zed');
INSERT INTO `champion` (`id`, `name`) VALUES ('115', 'Ziggs');
INSERT INTO `champion` (`id`, `name`) VALUES ('26', 'Zilean');
INSERT INTO `champion` (`id`, `name`) VALUES ('143', 'Zyra');

